### ISSUE TITLE
Shouldn't send class info with quoted messages

### ISSUE THREAD

**Issue by s-hfarooq** [timot3/uiuc-classes-bot#5]
Don't send info about classes if it is requested in a quoted message, may be seen as spam and is unnecessary 
![image](https://user-images.githubusercontent.com/20218462/82743442-5c396100-9d20-11ea-83a7-385114738d8d.png)

**Comment by timot3** [comment]
Is there a way to do this without ```if '> ' not in message.contents```? After reading the [Discord.py documentation](https://discordpy.readthedocs.io/en/latest/api.html?highlight=message#message), I could not find if a message has a `has_quote` property.

**Comment by s-hfarooq** [comment]
I think that might be the only way to do it. But you won't be able to ignore the rest of the message since something like this could occur

![image](https://user-images.githubusercontent.com/20218462/82744150-7cb9e900-9d29-11ea-824e-aa29f84873b9.png)

where the user would still want info about [ece408]

**Comment by timot3** [comment]
Issue should be resolved by parsing only the part of the message without the quote.
